trigger: none

pool:
  name: ADO-agent

stages:
- stage: Initialization
  displayName: Terraform Init

  jobs:
  - job: Init
    steps:
    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: azurerm
        command: init
        workingDirectory: '$(System.DefaultWorkingDirectory)'

        backendServiceArm: Connection-SVC
        backendAzureRmResourceGroupName: umbrella
        backendAzureRmStorageAccountName: itsisraningtoday2
        backendAzureRmContainerName: container
        backendAzureRmKey: terraform.tfstate

- stage: Planning
  displayName: Terraform Plan
  dependsOn: Initialization

  jobs:
  - job: Plan
    steps:
    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: azurerm
        command: init
        workingDirectory: '$(System.DefaultWorkingDirectory)'

        backendServiceArm: Connection-SVC
        backendAzureRmResourceGroupName: umbrella
        backendAzureRmStorageAccountName: itsisraningtoday2
        backendAzureRmContainerName: container
        backendAzureRmKey: terraform.tfstate

    - task: TerraformTask@5
      displayName: Terraform Plan
      inputs:
        provider: azurerm
        command: plan
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        environmentServiceNameAzureRM: Connection-SVC