trigger: none
pool: ADO-agent
stages:
  - stage: Initialization
    displayName: Terraform Init
    jobs:
      - job: Init
        displayName: Terraform Init
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'Connection-SVC'
              backendAzureRmResourceGroupName: 'umbrella'
              backendAzureRmStorageAccountName: 'itsisraningtoday2'
              backendAzureRmContainerName: 'container'
              backendAzureRmKey: 'terraform.tfstate'

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.SourcesDirectory)'
              artifact: 'terraform-init'
              publishLocation: 'pipeline'


  - stage: Planning
    displayName: Terraform Plan
    jobs:
      - job: Plan
        displayName: Terraform Plan
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              artifactName: 'terraform-init'
              targetPath: '(Pipeline.Workspace)/terraform'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'Connection-SVC'


  # - stage: Applying
  #   displayName: Terraform Apply
  #   jobs:
  #     - job: Apply
  #       displayName: Terraform Apply
  #       steps:
  #         - task: TerraformTask@5
  #           inputs:
  #             provider: 'azurerm'
  #             command: 'apply'
  #             environmentServiceNameAzureRM: 'Connection-SVC'
